### ISSUE TITLE
wrong "kind" keyword in covariances.coherence(kind='entropy')

### ISSUE THREAD

**Issue by tsawi** [covseisnet/covseisnet#1]
the [manual](https://covseisnet.gricad-pages.univ-grenoble-alpes.fr/covseisnet/api.html#covseisnet.covariancematrix.CovarianceMatrix.coherence) says "The entropy is obtained with setting kind='entropy'..." but I currently have to use keyword kind='coherence'

**Comment by FrancisTong** [comment]
Thanks for reporting this. It is fixed in the next release, version 0.5
