### ISSUE TITLE
/root/DEM.tif

### ISSUE THREAD

**Issue by smaher1** [covseisnet/covseisnet#3]
Hello, I am trying to run the example "plot_pdf_example.py" but I am stuck because it requires the file "/root/DEM.tif". Can you please upload the file? Thank you!

**Comment by FrancisTong** [comment]
Hello,
The example actually downloads the DEM using the python package Elevation. However, I understand that this package can be tricky to install. I've attached the DEM.tif file here so you can bypass the use of Elevation if you want. I hope this helps.
[DEM.zip](https://github.com/covseisnet/covseisnet/files/9380854/DEM.zip)
