### ISSUE TITLE
Traveltime File Path

### ISSUE THREAD

**Issue by brendan-mills** [covseisnet/covseisnet#4]
I am working through the "plot_pdf_example.py" file and there is a reference to traveltime grids (line 82) that were calculated before runtime. The file path refernced is used to create a traveltimes object that is used in creating the beam later on. Is there any information or code on how to calculate these traveltime files for an arbitrary network of stations? 
Thanks!

**Comment by FrancisTong** [comment]
Yes, I'll try to find an example for you.

**Comment by cyril-jrn** [comment]
Hello, 
Please find attached the document "instruction_travel_times_obspy_taup.pdf" containing some instructions to calculate the traveltime files using the obspy.taup package. 
Others possibilities are to use Nonlinloc (http://alomax.free.fr/nlloc/) or Pykonal (https://github.com/malcolmw/pykonal). You can find some notebooks here (https://github.com/ebeauce/beampower/tree/main/notebooks) where Pykonal is used to compute travel times given a velocity model.

[instruction_travel_times_obspy_taup.pdf](https://github.com/covseisnet/covseisnet/files/10065890/instruction_travel_times_obspy_taup.pdf)

**Comment by GPeng00** [comment]
According to the document "instruction_travel_times_obspy_taup.pdf", the resulted arrivals is NaN. My script is showed as follows

from obspy.taup import taup_create, TauPyModel
taup_create.build_taup_model('tc.tvel', output_folder='.')
velmodel = TauPyModel(model='tc.npz')
arrivals = velmodel.get_travel_times(source_depth_in_km=10, distance_in_degree=0.5, phase_list=['P', 'S'], receiver_depth_in_km=0)
print(arrivals)

The velocity model is showed as follows

# tc velocity model from Yao et al. 2018
# depth p s density
0.0 4.81 2.85 2.51
2.0 5.16 3.06 2.56
4.0 5.48 3.24 2.62
6.0 5.76 3.40 2.67
8.0 5.85 3.44 2.69  
10.0 6.10 3.58 2.74
16.0 6.00 3.52 2.72 
20.0 5.86 3.45 2.69
26.0 5.96 3.50 2.71
30.0 5.98 3.51 2.72 
40.0 6.94 4.00 2.96 
52.0 7.82 4.46 3.23

I think many people encountering  similar issues how to compute the travel times.  We are grateful if you can provide an example in file folder examples.

**Comment by GPeng00** [comment]
According to the document "instruction_travel_times_obspy_taup.pdf", the resulted arrivals is NaN. My script is showed as follows

from obspy.taup import taup_create, TauPyModel
taup_create.build_taup_model('tc.tvel', output_folder='.')
velmodel = TauPyModel(model='tc.npz')
arrivals = velmodel.get_travel_times(source_depth_in_km=10, distance_in_degree=0.5, phase_list=['P', 'S'], receiver_depth_in_km=0)
print(arrivals)

The velocity model is showed as follows

0.0 4.81 2.85 2.51
2.0 5.16 3.06 2.56
4.0 5.48 3.24 2.62
6.0 5.76 3.40 2.67
8.0 5.85 3.44 2.69  
10.0 6.10 3.58 2.74
16.0 6.00 3.52 2.72 
20.0 5.86 3.45 2.69
26.0 5.96 3.50 2.71
30.0 5.98 3.51 2.72 
40.0 6.94 4.00 2.96 
52.0 7.82 4.46 3.23

I think many people encountering  similar issues how to compute the travel times.  We are grateful if you can provide an example in file folder examples.
